//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace frontend.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GymMeWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GymMeWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback registerNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateUserProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupplementListOperationCompleted;
        
        private System.Threading.SendOrPostCallback addNewCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCartListOperationCompleted;
        
        private System.Threading.SendOrPostCallback clearCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback createNewTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTransactionHeaderByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTransactionHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTransactionDetailByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback createNewSupplementOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateSupplementOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteSupplementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GymMeWebService() {
            this.Url = global::frontend.Properties.Settings.Default.frontend_localhost_GymMeWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event registerNewUserCompletedEventHandler registerNewUserCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event updateUserProfileCompletedEventHandler updateUserProfileCompleted;
        
        /// <remarks/>
        public event changeUserPasswordCompletedEventHandler changeUserPasswordCompleted;
        
        /// <remarks/>
        public event getUserCompletedEventHandler getUserCompleted;
        
        /// <remarks/>
        public event getAllUserCompletedEventHandler getAllUserCompleted;
        
        /// <remarks/>
        public event getSupplementListCompletedEventHandler getSupplementListCompleted;
        
        /// <remarks/>
        public event addNewCartCompletedEventHandler addNewCartCompleted;
        
        /// <remarks/>
        public event getCartListCompletedEventHandler getCartListCompleted;
        
        /// <remarks/>
        public event clearCartCompletedEventHandler clearCartCompleted;
        
        /// <remarks/>
        public event createNewTransactionCompletedEventHandler createNewTransactionCompleted;
        
        /// <remarks/>
        public event getAllTransactionHeaderByIdCompletedEventHandler getAllTransactionHeaderByIdCompleted;
        
        /// <remarks/>
        public event getAllTransactionHeaderCompletedEventHandler getAllTransactionHeaderCompleted;
        
        /// <remarks/>
        public event getAllTransactionDetailByIdCompletedEventHandler getAllTransactionDetailByIdCompleted;
        
        /// <remarks/>
        public event updateTransactionStatusCompletedEventHandler updateTransactionStatusCompleted;
        
        /// <remarks/>
        public event createNewSupplementCompletedEventHandler createNewSupplementCompleted;
        
        /// <remarks/>
        public event updateSupplementCompletedEventHandler updateSupplementCompleted;
        
        /// <remarks/>
        public event deleteSupplementCompletedEventHandler deleteSupplementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registerNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registerNewUser(string username, string email, string password, System.DateTime DOB, string gender, string role) {
            this.Invoke("registerNewUser", new object[] {
                        username,
                        email,
                        password,
                        DOB,
                        gender,
                        role});
        }
        
        /// <remarks/>
        public void registerNewUserAsync(string username, string email, string password, System.DateTime DOB, string gender, string role) {
            this.registerNewUserAsync(username, email, password, DOB, gender, role, null);
        }
        
        /// <remarks/>
        public void registerNewUserAsync(string username, string email, string password, System.DateTime DOB, string gender, string role, object userState) {
            if ((this.registerNewUserOperationCompleted == null)) {
                this.registerNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterNewUserOperationCompleted);
            }
            this.InvokeAsync("registerNewUser", new object[] {
                        username,
                        email,
                        password,
                        DOB,
                        gender,
                        role}, this.registerNewUserOperationCompleted, userState);
        }
        
        private void OnregisterNewUserOperationCompleted(object arg) {
            if ((this.registerNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerNewUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string username, string password) {
            object[] results = this.Invoke("login", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password) {
            this.loginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        username,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateUserProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateUserProfile(int id, string username, string email, System.DateTime DOB, string gender, string role) {
            object[] results = this.Invoke("updateUserProfile", new object[] {
                        id,
                        username,
                        email,
                        DOB,
                        gender,
                        role});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateUserProfileAsync(int id, string username, string email, System.DateTime DOB, string gender, string role) {
            this.updateUserProfileAsync(id, username, email, DOB, gender, role, null);
        }
        
        /// <remarks/>
        public void updateUserProfileAsync(int id, string username, string email, System.DateTime DOB, string gender, string role, object userState) {
            if ((this.updateUserProfileOperationCompleted == null)) {
                this.updateUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUserProfileOperationCompleted);
            }
            this.InvokeAsync("updateUserProfile", new object[] {
                        id,
                        username,
                        email,
                        DOB,
                        gender,
                        role}, this.updateUserProfileOperationCompleted, userState);
        }
        
        private void OnupdateUserProfileOperationCompleted(object arg) {
            if ((this.updateUserProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateUserProfileCompleted(this, new updateUserProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/changeUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string changeUserPassword(string username, string oldPassword, string newPassword) {
            object[] results = this.Invoke("changeUserPassword", new object[] {
                        username,
                        oldPassword,
                        newPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changeUserPasswordAsync(string username, string oldPassword, string newPassword) {
            this.changeUserPasswordAsync(username, oldPassword, newPassword, null);
        }
        
        /// <remarks/>
        public void changeUserPasswordAsync(string username, string oldPassword, string newPassword, object userState) {
            if ((this.changeUserPasswordOperationCompleted == null)) {
                this.changeUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeUserPasswordOperationCompleted);
            }
            this.InvokeAsync("changeUserPassword", new object[] {
                        username,
                        oldPassword,
                        newPassword}, this.changeUserPasswordOperationCompleted, userState);
        }
        
        private void OnchangeUserPasswordOperationCompleted(object arg) {
            if ((this.changeUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeUserPasswordCompleted(this, new changeUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getUser(string username) {
            object[] results = this.Invoke("getUser", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserAsync(string username) {
            this.getUserAsync(username, null);
        }
        
        /// <remarks/>
        public void getUserAsync(string username, object userState) {
            if ((this.getUserOperationCompleted == null)) {
                this.getUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserOperationCompleted);
            }
            this.InvokeAsync("getUser", new object[] {
                        username}, this.getUserOperationCompleted, userState);
        }
        
        private void OngetUserOperationCompleted(object arg) {
            if ((this.getUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCompleted(this, new getUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllUser() {
            object[] results = this.Invoke("getAllUser", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllUserAsync() {
            this.getAllUserAsync(null);
        }
        
        /// <remarks/>
        public void getAllUserAsync(object userState) {
            if ((this.getAllUserOperationCompleted == null)) {
                this.getAllUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllUserOperationCompleted);
            }
            this.InvokeAsync("getAllUser", new object[0], this.getAllUserOperationCompleted, userState);
        }
        
        private void OngetAllUserOperationCompleted(object arg) {
            if ((this.getAllUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllUserCompleted(this, new getAllUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSupplementList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSupplementList() {
            object[] results = this.Invoke("getSupplementList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSupplementListAsync() {
            this.getSupplementListAsync(null);
        }
        
        /// <remarks/>
        public void getSupplementListAsync(object userState) {
            if ((this.getSupplementListOperationCompleted == null)) {
                this.getSupplementListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupplementListOperationCompleted);
            }
            this.InvokeAsync("getSupplementList", new object[0], this.getSupplementListOperationCompleted, userState);
        }
        
        private void OngetSupplementListOperationCompleted(object arg) {
            if ((this.getSupplementListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupplementListCompleted(this, new getSupplementListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addNewCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addNewCart(int userId, int supplementId, int quantity) {
            this.Invoke("addNewCart", new object[] {
                        userId,
                        supplementId,
                        quantity});
        }
        
        /// <remarks/>
        public void addNewCartAsync(int userId, int supplementId, int quantity) {
            this.addNewCartAsync(userId, supplementId, quantity, null);
        }
        
        /// <remarks/>
        public void addNewCartAsync(int userId, int supplementId, int quantity, object userState) {
            if ((this.addNewCartOperationCompleted == null)) {
                this.addNewCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddNewCartOperationCompleted);
            }
            this.InvokeAsync("addNewCart", new object[] {
                        userId,
                        supplementId,
                        quantity}, this.addNewCartOperationCompleted, userState);
        }
        
        private void OnaddNewCartOperationCompleted(object arg) {
            if ((this.addNewCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addNewCartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCartList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCartList(int id) {
            object[] results = this.Invoke("getCartList", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCartListAsync(int id) {
            this.getCartListAsync(id, null);
        }
        
        /// <remarks/>
        public void getCartListAsync(int id, object userState) {
            if ((this.getCartListOperationCompleted == null)) {
                this.getCartListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCartListOperationCompleted);
            }
            this.InvokeAsync("getCartList", new object[] {
                        id}, this.getCartListOperationCompleted, userState);
        }
        
        private void OngetCartListOperationCompleted(object arg) {
            if ((this.getCartListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCartListCompleted(this, new getCartListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/clearCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void clearCart(int id) {
            this.Invoke("clearCart", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void clearCartAsync(int id) {
            this.clearCartAsync(id, null);
        }
        
        /// <remarks/>
        public void clearCartAsync(int id, object userState) {
            if ((this.clearCartOperationCompleted == null)) {
                this.clearCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnclearCartOperationCompleted);
            }
            this.InvokeAsync("clearCart", new object[] {
                        id}, this.clearCartOperationCompleted, userState);
        }
        
        private void OnclearCartOperationCompleted(object arg) {
            if ((this.clearCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.clearCartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createNewTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewTransaction(int id) {
            this.Invoke("createNewTransaction", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void createNewTransactionAsync(int id) {
            this.createNewTransactionAsync(id, null);
        }
        
        /// <remarks/>
        public void createNewTransactionAsync(int id, object userState) {
            if ((this.createNewTransactionOperationCompleted == null)) {
                this.createNewTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateNewTransactionOperationCompleted);
            }
            this.InvokeAsync("createNewTransaction", new object[] {
                        id}, this.createNewTransactionOperationCompleted, userState);
        }
        
        private void OncreateNewTransactionOperationCompleted(object arg) {
            if ((this.createNewTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createNewTransactionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllTransactionHeaderById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllTransactionHeaderById(int id) {
            object[] results = this.Invoke("getAllTransactionHeaderById", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTransactionHeaderByIdAsync(int id) {
            this.getAllTransactionHeaderByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void getAllTransactionHeaderByIdAsync(int id, object userState) {
            if ((this.getAllTransactionHeaderByIdOperationCompleted == null)) {
                this.getAllTransactionHeaderByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTransactionHeaderByIdOperationCompleted);
            }
            this.InvokeAsync("getAllTransactionHeaderById", new object[] {
                        id}, this.getAllTransactionHeaderByIdOperationCompleted, userState);
        }
        
        private void OngetAllTransactionHeaderByIdOperationCompleted(object arg) {
            if ((this.getAllTransactionHeaderByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTransactionHeaderByIdCompleted(this, new getAllTransactionHeaderByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllTransactionHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllTransactionHeader() {
            object[] results = this.Invoke("getAllTransactionHeader", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTransactionHeaderAsync() {
            this.getAllTransactionHeaderAsync(null);
        }
        
        /// <remarks/>
        public void getAllTransactionHeaderAsync(object userState) {
            if ((this.getAllTransactionHeaderOperationCompleted == null)) {
                this.getAllTransactionHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTransactionHeaderOperationCompleted);
            }
            this.InvokeAsync("getAllTransactionHeader", new object[0], this.getAllTransactionHeaderOperationCompleted, userState);
        }
        
        private void OngetAllTransactionHeaderOperationCompleted(object arg) {
            if ((this.getAllTransactionHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTransactionHeaderCompleted(this, new getAllTransactionHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllTransactionDetailById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllTransactionDetailById(int id) {
            object[] results = this.Invoke("getAllTransactionDetailById", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTransactionDetailByIdAsync(int id) {
            this.getAllTransactionDetailByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void getAllTransactionDetailByIdAsync(int id, object userState) {
            if ((this.getAllTransactionDetailByIdOperationCompleted == null)) {
                this.getAllTransactionDetailByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTransactionDetailByIdOperationCompleted);
            }
            this.InvokeAsync("getAllTransactionDetailById", new object[] {
                        id}, this.getAllTransactionDetailByIdOperationCompleted, userState);
        }
        
        private void OngetAllTransactionDetailByIdOperationCompleted(object arg) {
            if ((this.getAllTransactionDetailByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTransactionDetailByIdCompleted(this, new getAllTransactionDetailByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateTransactionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateTransactionStatus(int id) {
            this.Invoke("updateTransactionStatus", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void updateTransactionStatusAsync(int id) {
            this.updateTransactionStatusAsync(id, null);
        }
        
        /// <remarks/>
        public void updateTransactionStatusAsync(int id, object userState) {
            if ((this.updateTransactionStatusOperationCompleted == null)) {
                this.updateTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("updateTransactionStatus", new object[] {
                        id}, this.updateTransactionStatusOperationCompleted, userState);
        }
        
        private void OnupdateTransactionStatusOperationCompleted(object arg) {
            if ((this.updateTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateTransactionStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createNewSupplement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewSupplement(string name, System.DateTime date, int price, int TypeId) {
            this.Invoke("createNewSupplement", new object[] {
                        name,
                        date,
                        price,
                        TypeId});
        }
        
        /// <remarks/>
        public void createNewSupplementAsync(string name, System.DateTime date, int price, int TypeId) {
            this.createNewSupplementAsync(name, date, price, TypeId, null);
        }
        
        /// <remarks/>
        public void createNewSupplementAsync(string name, System.DateTime date, int price, int TypeId, object userState) {
            if ((this.createNewSupplementOperationCompleted == null)) {
                this.createNewSupplementOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateNewSupplementOperationCompleted);
            }
            this.InvokeAsync("createNewSupplement", new object[] {
                        name,
                        date,
                        price,
                        TypeId}, this.createNewSupplementOperationCompleted, userState);
        }
        
        private void OncreateNewSupplementOperationCompleted(object arg) {
            if ((this.createNewSupplementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createNewSupplementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateSupplement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateSupplement(int supplementId, string name, System.DateTime date, int price, int TypeId) {
            this.Invoke("updateSupplement", new object[] {
                        supplementId,
                        name,
                        date,
                        price,
                        TypeId});
        }
        
        /// <remarks/>
        public void updateSupplementAsync(int supplementId, string name, System.DateTime date, int price, int TypeId) {
            this.updateSupplementAsync(supplementId, name, date, price, TypeId, null);
        }
        
        /// <remarks/>
        public void updateSupplementAsync(int supplementId, string name, System.DateTime date, int price, int TypeId, object userState) {
            if ((this.updateSupplementOperationCompleted == null)) {
                this.updateSupplementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateSupplementOperationCompleted);
            }
            this.InvokeAsync("updateSupplement", new object[] {
                        supplementId,
                        name,
                        date,
                        price,
                        TypeId}, this.updateSupplementOperationCompleted, userState);
        }
        
        private void OnupdateSupplementOperationCompleted(object arg) {
            if ((this.updateSupplementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateSupplementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteSupplement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteSupplement(int supplementId) {
            this.Invoke("deleteSupplement", new object[] {
                        supplementId});
        }
        
        /// <remarks/>
        public void deleteSupplementAsync(int supplementId) {
            this.deleteSupplementAsync(supplementId, null);
        }
        
        /// <remarks/>
        public void deleteSupplementAsync(int supplementId, object userState) {
            if ((this.deleteSupplementOperationCompleted == null)) {
                this.deleteSupplementOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteSupplementOperationCompleted);
            }
            this.InvokeAsync("deleteSupplement", new object[] {
                        supplementId}, this.deleteSupplementOperationCompleted, userState);
        }
        
        private void OndeleteSupplementOperationCompleted(object arg) {
            if ((this.deleteSupplementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteSupplementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void registerNewUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void updateUserProfileCompletedEventHandler(object sender, updateUserProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void changeUserPasswordCompletedEventHandler(object sender, changeUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getUserCompletedEventHandler(object sender, getUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAllUserCompletedEventHandler(object sender, getAllUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getSupplementListCompletedEventHandler(object sender, getSupplementListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupplementListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupplementListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void addNewCartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCartListCompletedEventHandler(object sender, getCartListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCartListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCartListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void clearCartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void createNewTransactionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAllTransactionHeaderByIdCompletedEventHandler(object sender, getAllTransactionHeaderByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTransactionHeaderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTransactionHeaderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAllTransactionHeaderCompletedEventHandler(object sender, getAllTransactionHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTransactionHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTransactionHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAllTransactionDetailByIdCompletedEventHandler(object sender, getAllTransactionDetailByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTransactionDetailByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTransactionDetailByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void updateTransactionStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void createNewSupplementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void updateSupplementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void deleteSupplementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591